package com.iit.movie.MovieService.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.iit.movie.MovieService.model.User;
import com.iit.movie.MovieService.repository.UserRepository;

@Service
public class UserServiceImpl implements UserService {

	private UserRepository userRepository; 
	 
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	public void setUserRepository(UserRepository userRepository) {
		this.userRepository = userRepository;
	}

	
	@Override
	public Iterable<User> listAll() { 
		return userRepository.findAll();
	}

	@Override
	public User getById(User user) { 
		return userRepository.findOne(user.getId());
	}

	@Override
	public User save(User user) {
		 
		return userRepository.save(user);
	}

	@Override
	public void delete(User user) {
		userRepository.delete(user.getId());
		
	}

}
